### ISSUE TITLE
Not working, plenty of glitches

### ISSUE THREAD

**Issue by jmfergeau** [StarsoftAnalysis/MediaOrganiser#1]
First, thank you so much for doing this. I used to use "Media File Manager" by Atsushi Ueda and this one suddenly stopped working (like, i couldn't move the files and all) and also completely disappeared from the web with its author. I'm desperately in search for a similar plugin that works and it's how i found yours.

Trying it on my install and it's not working well. There's two noticeable things I seen:

First, the folders pictures shows 404. Probably because the tag points to a relative `dir.png` instead of a full path.
Second, it simply considers all my files are "missing" while they're indeed there.
Also the folders are the one in the root of the server (usr, var, etc,...) while the files in the `upload` folders are displaying right. I'm not sure it's what's intended.

Thanks in advance

**Comment by StarsoftAnalysis** [comment]
Sorry, but I can't offer support for MediaOrganiser any more -- I haven't worked with WordPress for years.
